version: '3.5'

services:
  postgres:
    container_name: people_container
    image: postgres
    environment:
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
      PGDATA: /data/people
    volumes:
      - postgres:/data/people
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: