version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: people
      MYSQL_DATABASE: people
      MYSQL_USER: people
      MYSQL_PASSWORD: people
    ports:
      - "3306:3306"